# Generated by Django 2.2.7 on 2019-11-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20191120_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nama_barang',
            new_name='nama',
        ),
    ]
