# Generated by Django 2.2.7 on 2019-11-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20191120_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gambar',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
