# Generated by Django 2.2.7 on 2019-11-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20191120_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='id',
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
