# Generated by Django 2.2.7 on 2019-11-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20191120_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='fakultas',
        ),
    ]
